### ISSUE TITLE
typo in use of tablecloth/drop-missing?

### ISSUE THREAD

**Issue by daslu** [scicloj/scicloj-data-science-handbook#4]
Hi @kimim !

Looking at your wonderful work on chapter 3, I ran into this:

https://github.com/scicloj/scicloj-data-science-handbook/blob/8109e9dd9ab7e0037e3968ce4753665c56a1d67e/src/scicloj/03_data_manipulation/04_missing_values.clj#L172

```clj
(tablecloth/drop-missing DS :A)
```
I'm not sure what was supposed to be here. This does not work, as `DS` does not have an `:A` column.
Probably a typo?

**Comment by kimim** [comment]
The code is partially complete, when I am thinking the relationship between NaN and nil. Now I've fix the broken. Thanks.

**Comment by daslu** [comment]
Thanks, @kimim !
